services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8787:8787"
    volumes:
      - /Users/evanrr/Developer/carcalc:/home/rstudio/carcalc
    working_dir: /home/rstudio/carcalc
    environment:
      PASSWORD: ""
